[tool.poetry]
name = "wonda"
version = "0.1.0"
description = "Asynchronous, feature-rich, high performant Telegram Bot API framework for building stunning bots"
authors = []
license = "MIT"
readme = "README.md"
homepage = "https://pypi.org/project/wonda/"

[tool.poetry.dependencies]
python = "^3.8"
choicelib = "^0.1.5"
pydantic = "^1.9.0"
aiohttp = "^3.8.1"
certifi = "^2022.6.15"
typing-extensions = "^4.3.0"
orjson = {version = "^3.7.11", optional = true}
uvloop = {version = "^0.16.0", optional = true}
watchfiles = {version = "^0.16.0", optional = true}

[tool.poetry.dev-dependencies]
isort = "^5.10.1"
black = "^22.6.0"

[tool.poetry.extras]
auto-reload = ["watchfiles"]
power-ups = ["orjson", "uvloop"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
